upgrades_table: public.upgrades
delta_dir: /home/mario/Dropbox/AA Tardis/Opengis/qWat/db/delta
backup_file: /tmp/test_dumper/backup.dump
ignore_elements:
  - tables
  - columns
  - constraints
  - views
  - sequences
  - indexes
  - triggers
  - functions
  - rules