
services:
  db:
    build:
      context: .
      dockerfile: datamodel/.docker/Dockerfile
      args:
        POSTGIS_IMAGE: ${POSTGIS_IMAGE:-postgis/postgis:16-3.5}
    image: qwat/qwat-data-model:${DOCKER_TAG:-unstable}
    working_dir: /src
    volumes:
      - .:/src
    ports:
      # making the postgres database accessible for debugging
      - ${QWAT_PG_PORT:-5432}:${QWAT_PG_PORT:-5432}

  qgis:
    build:
      context: .
      dockerfile: plugin/.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION:-latest}
    tty: true
    volumes:
      - .:/usr/src
    links:
      - db
    profiles:
      - qgis

  schemaspy:
    image: schemaspy/schemaspy
    volumes:
      - ./datamodel/schemaspy:/output
      - ./datamodel/schemaspy.properties:/schemaspy.properties
    depends_on:
      - db
    network_mode: "service:db"
    command: [
      "-configFile",
      "/schemaspy.properties"
    ]
    user: "${UID}:${GID}"
    profiles:
      - schemaspy
