name: Run tests

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

  release:
    types: ['prereleased', 'released']


jobs:

  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:9.6-2.5
        env:
          POSTGRES_DB: qwat_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGSERVICEFILE: ${{github.workspace}}/tests/pg_service.conf

    steps:

      - uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: tests/tests.sh

      - name: Run scalability tests
        run: tests/tests_scalability.sh -i 20

      - name: Run scalability tests multithreaded
        run: tests/tests_scalability_multithread.sh -i 20

      - name: Run upgrade tests
        run: tests/tests_upgrade.sh
